### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoshader#120]
The current documentation is/will be outdated as we progress on refactoring, so before the first release let's update the documentation to reflect all changes and update the example notebooks.

### Tasks
- [x] Add a brief introduction for echoshader
- [x] Add installation instructions
- [x] Update example notebooks, so that each suite of functionalities are demonstrated in a notebook. Also need 1-2 notebooks to demonstrate how to put multiple functionalities together and set up a server.
- [x] Designing philosophy and description about the structure

**Comment by ldr426** [comment]
Also add designing philosophy and description about the structure.
