### ISSUE TITLE
Create first release

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoshader#121]
Once all tasks are completed for echoshader, let's publish the first release! Once we have the first release, we'll work on getting the package onto conda-forge and automatic push to PyPI after each release, mimicking the current setup in echopype.

### Tasks
- [x] Set up webhook for Zenodo
- [x] Create release on GitHub
- [x] Submit to test PyPI
- [x] Submit to official PyPI
- [x] Ensure can pip install directly from PyPI
- [x] Update pip install instructions in docs to use pypi

**Comment by leewujung** [comment]
This will be resolved once #161 is merged.

**Comment by valentina-s** [comment]
Released.
